spring:
  datasource:
    username: ${app.db.username}
    password: ${app.db.password}
    url: jdbc:mysql://${app.db.host}:${app.db.port}/${app.db.schema}?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    tomcat:
      test-while-idle: true
      validation-query: 1
  #spring.jpa.database-platform=org.hibernate.dialect.MySQL57Dialect
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #    database-platform: org.hibernate.dialect.MySQL57Dialect


app:
  db:
    username: ${SERVICE_DB_USERNAME:root}
    password: ${SERVICE_DB_PASSWORD:Nurlan127}
    host: ${SERVICE_DB_HOST:localhost}
    schema: ${SERVICE_DB_SCHEMA:depozit}
    port: ${SERVICE_DB_PORT:3306}

